# 数据操作

In [1]:
import torch

### torch里面张量是一维数组，对应数学里面的向量(vector);具有两个轴的张量对应矩阵，多维则没有名字

In [7]:
x = torch.tensor([0,1,2,3,4,5,6,7,8,9,10,11])
y = torch.arange(12)
print(x)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [8]:
print(x.size())
print(y.size())

torch.Size([12])
torch.Size([12])


In [10]:
print(x.numel())

12


### 改变一个张量的形状而不改变张量的元素，可以用reshape()

In [11]:
X = x.reshape(3,4)
print(X)
print(X.size())
print(X.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12


In [13]:
# 创建一些特别的函数
# 1.全零函数
zero1 = torch.zeros(3,4)
print(zero1)
one1 = torch.ones(4,3)
print(one1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [16]:
# 创建特定的值
# 大[]里面加小[],跟线性代数的矩阵含义一样
z = torch.tensor([[1,2,3],[4,5,6]])
print(z)
print(z.size())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


### 张量的加减乘除运算

In [19]:
x1 = torch.tensor([1.0,2,4,8])
y1 = torch.tensor([2,2,2,2])
print(x1+y1)
print(x1-y1)
print(x1*y1)
print(x1/y1)
print(x1**y1)  # 求幂运算

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


### 将张量结合起来

In [26]:
x2 = torch.arange(12,dtype=torch.float32).reshape(3,4)
y2 = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# dim是按照维度来拼接，dim=0是一维
print(torch.cat((x2,y2),dim=0))
print(torch.cat((x2,y2),dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [29]:
x3 = torch.arange(12,dtype=torch.float32).reshape(3,2,2)
y3 = torch.arange(12,dtype=torch.float32).reshape(3,2,2)
# dim是按照维度来拼接，dim=0是一维
# 如果不理解请看 "["
print(torch.cat((x3,y3),dim=0))
print(torch.cat((x3,y3),dim=1))
print(torch.cat((x3,y3),dim=2))

tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]],

        [[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]])
tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [ 8.,  9.],
         [10., 11.]]])
tensor([[[ 0.,  1.,  0.,  1.],
         [ 2.,  3.,  2.,  3.]],

        [[ 4.,  5.,  4.,  5.],
         [ 6.,  7.,  6.,  7.]],

        [[ 8.,  9.,  8.,  9.],
         [10., 11., 10., 11.]]])


In [30]:
# 对张量求和
x3.sum()

tensor(66.)

### 即使两个张量形状不同，仍可以通过广播机制来执行元素操作

In [31]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


### 元素的访问

In [34]:
x = torch.arange(12).reshape((3,4))
print(x)
print(x[-1])
print(x[1:3])
print(x[:,1])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 8,  9, 10, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([1, 5, 9])
